apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${endpoint}
spec:
  acme:
    email: admin@meissa-gmbh.de
    server: https://acme-${endpoint}-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: ${endpoint}
    solvers:
    - http01:
        ingress:
          class:  traefik

