default-local-storage-path: /var
tls-san: ${tls_name}
kube-proxy-arg proxy-mode: ipvs
disable-network-policy: true
disable-cloud-controller: true
disable:
  - servicelb
cluster-cidr:
  - 10.42.0.0/16
service-cidr:
  - 10.43.0.0/16
node-ip:
  - ${node_ipv4}
bind-address: ${loopback_ipv4}
advertise-address: ${loopback_ipv4}