apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public
  namespace: metallb-system
spec:
  addresses:
  - ${node_ipv4}/32
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: private
  namespace: metallb-system
spec:
  addresses:
  - ${loopback_ipv4}/32